/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbs_project;

import java.security.MessageDigest;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.xml.bind.DatatypeConverter;

/**
 *
 * @author sichi
 */
public class Register_Warden extends javax.swing.JFrame {

    /**
     * Creates new form Register_Warden
     */
    public Register_Warden() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tf4 = new javax.swing.JTextField();
        tf3 = new javax.swing.JTextField();
        tf6 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tf8 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf7 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        register = new javax.swing.JButton();
        pw = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf9 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(tf5, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 159, 82, -1));

        jLabel5.setText("Block No :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 189, -1, -1));

        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Phone Number :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 249, -1, -1));

        jLabel8.setText("Email ID :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 218, -1, -1));

        jButton1.setText("Capture Image");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 322, -1, -1));
        getContentPane().add(tf4, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 128, 82, -1));
        getContentPane().add(tf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 102, 82, -1));
        getContentPane().add(tf6, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 186, 82, -1));

        jLabel1.setText("Name :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 131, -1, -1));
        getContentPane().add(tf8, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 246, 80, -1));

        jLabel2.setText("Warden ID :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 105, -1, -1));
        getContentPane().add(tf7, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 215, 84, -1));

        jLabel3.setText("Date Of Birth :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 162, -1, -1));

        register.setText("Register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        getContentPane().add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 360, -1, -1));
        getContentPane().add(pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 78, 82, -1));

        jLabel4.setText("Username:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 58, -1, -1));

        jLabel6.setText("Password:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 81, -1, -1));

        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        getContentPane().add(tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 52, 82, -1));

        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Address ;");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 287, -1, -1));
        getContentPane().add(tf9, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 284, 80, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbs_project/d_login.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents
int flag=0;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Warden.wID=Integer.parseInt(tf3.getText());
        new WebCapture(0);
        JOptionPane.showMessageDialog(null,"Photo taken Successfuly");
        flag=1;
    }//GEN-LAST:event_jButton1ActionPerformed
private boolean validate_login(String username,String password) {
   try{          //Connection Code 
        // MySQL database connection
       Connection conn = Conn.connect();
       PreparedStatement pst =   conn.prepareStatement("insert into login values('"+username+"' , '"+password+"')");
       pst.executeUpdate();
       PreparedStatement pst1 = conn.prepareStatement("insert into warden_details values("+tf3.getText()+",'"
                                                                                    +tf4.getText()+"','"
                                                                                    +tf8.getText()+"','"
                                                                                    +tf6.getText()+"','"
                                                                                    +username+"')");
       pst1.executeUpdate();
       conn.close();
       return true;           
   }
   catch(Exception e){
       e.printStackTrace();
       return false;
   }       
}
    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        if(flag==0 || tf1.getText()==null
                   || pw.getText()==null
                   || tf3.getText()==null
                   || tf4.getText()==null
                   || tf5.getText()==null
                   || tf6.getText()==null
                   || tf7.getText()==null
                   || tf8.getText()==null){
            JOptionPane.showMessageDialog(null,"Please fill all details");
            return;
            
        }
        String username = tf1.getText();
        String password = new String(pw.getPassword());
        String hashedPassword = password;
        // String hashedPassword = generateHash(password);
        MessageDigest digest;
        try {
            digest = MessageDigest.getInstance("SHA-256");

            byte[] hash = digest.digest(password.getBytes("UTF-8"));
            hashedPassword = DatatypeConverter.printHexBinary(hash);
        } catch (Exception ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(validate_login(username,hashedPassword)){
            JOptionPane.showMessageDialog(null, "Registration Successful");
            new Login().setVisible(true);
            this.setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(null, "Registration Failed\nUsername already in use.");
            tf1.setText("");
            pw.setText("");
        }
                if(flag==0 || tf1.getText()==null
                   || tf3.getText()==null
                   || tf4.getText()==null
                   || tf5.getText()==null
                   || tf6.getText()==null
                   || tf7.getText()==null
                   || tf8.getText()==null
                   || tf9.getText()==null
                   
                   ){
            JOptionPane.showMessageDialog(null,"Please fill all details");
            return;
        }
        else{
            String Warden_ID=tf3.getText();
            String Name =tf4.getText();
            String D_O_B =tf5.getText();
            String Block =tf6.getText();
            String Email =tf7.getText();
            String phone =tf8.getText();
            String Address =tf9.getText();
            String uname=tf1.getText();
            String pass=pw.getText();
            try {
               Connection conn = Conn.connect();
               PreparedStatement pst =   conn.prepareStatement("insert into warden_details values('"+Warden_ID+"','"+Name+"','"+D_O_B+"','"+Block+"','"+Email+"','"+phone+"','"+Address+"','"+uname+"')");
               pst.execute();
               String password1=HashingPassword.hashPassword(pass);
               PreparedStatement pst1 =   conn.prepareStatement("insert into login values('"+uname+"','"+password1+"')");
               pst1.execute();
               conn.close();
           } catch (SQLException ex) {
               Logger.getLogger(AddWatchlistEntry.class.getName()).log(Level.SEVERE, null, ex);
           }
            
            JOptionPane.showMessageDialog(null,"Submitted Succesfully");
            
            
            
        }
    }//GEN-LAST:event_registerActionPerformed

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_Warden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_Warden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_Warden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_Warden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_Warden().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField pw;
    private javax.swing.JButton register;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextField tf5;
    private javax.swing.JTextField tf6;
    private javax.swing.JTextField tf7;
    private javax.swing.JTextField tf8;
    private javax.swing.JTextField tf9;
    // End of variables declaration//GEN-END:variables
}
